import { DataSource, SourceType } from "@vbkg/types";

export const mockDataSources: DataSource[] = [
  {
    id: "ds-1",
    name: "Khách hàng CSV",
    description: "File CSV chứa dữ liệu khách hàng",
    source_type: SourceType.FILE,
    connection_details: {
      file_path: "/data/customers.csv",
      file_format: "csv",
      encoding: "utf-8",
      delimiter: ",",
    },
    is_active: true,
    created_by: "admin@example.com",
    created_at: "2025-04-15T10:30:00Z",
    updated_at: "2025-04-15T10:30:00Z",
  },
  {
    id: "ds-2",
    name: "API Sản phẩm",
    description: "API lấy thông tin sản phẩm",
    source_type: SourceType.API,
    connection_details: {
      url: "https://api.example.com/products",
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer {token}",
      },
    },
    is_active: true,
    created_by: "admin@example.com",
    created_at: "2025-04-10T14:20:00Z",
    updated_at: "2025-04-12T09:15:00Z",
  },
  {
    id: "ds-3",
    name: "Database Đơn hàng",
    description: "Cơ sở dữ liệu PostgreSQL chứa đơn hàng",
    source_type: SourceType.DATABASE,
    connection_details: {
      host: "db.example.com",
      port: 5432,
      database: "orders_db",
      username: "read_user",
      db_type: "postgres",
      ssl: true,
      table: "orders",
    },
    is_active: false,
    created_by: "admin@example.com",
    created_at: "2025-03-20T08:45:00Z",
    updated_at: "2025-04-05T16:30:00Z",
  },
  {
    id: "ds-4",
    name: "Website Tin tức",
    description: "Trang web chứa các bài viết tin tức",
    source_type: SourceType.URL,
    connection_details: {
      url: "https://news.example.com",
      scrape_config: {
        selector: "article.news-item",
        fields: {
          title: "h2",
          content: "div.content",
          date: "span.date",
        },
      },
    },
    is_active: true,
    created_by: "user@example.com",
    created_at: "2025-04-01T11:10:00Z",
    updated_at: "2025-04-01T11:10:00Z",
  },
  {
    id: "ds-5",
    name: "Dữ liệu Excel",
    description: "File Excel chứa dữ liệu thống kê",
    source_type: SourceType.FILE,
    connection_details: {
      file_path: "/data/statistics.xlsx",
      file_format: "xlsx",
      encoding: "utf-8",
    },
    is_active: true,
    created_by: "admin@example.com",
    created_at: "2025-04-20T09:15:00Z",
    updated_at: "2025-04-20T09:15:00Z",
  },
];
